-- =======================================================
-- HOTEL MANAGEMENT V2 (Multi-Branch Architecture)
-- =======================================================

-- 1. Branches (Sedes)
CREATE TABLE IF NOT EXISTS branches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    city TEXT,
    address TEXT,
    phone TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Floors (Pisos) / Houses (Casas) / Zones (Zonas)
CREATE TABLE IF NOT EXISTS floors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT REFERENCES branches(id) ON DELETE CASCADE,
    floor_number INTEGER NOT NULL,
    name TEXT, -- "Piso 1", "Cabaña A", "Zona Piscina"
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(branch_id, floor_number) -- A zone number (or floor number) is unique per branch
);

-- 3. Rooms (Habitaciones)
CREATE TABLE IF NOT EXISTS rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT REFERENCES branches(id) ON DELETE CASCADE,
    floor_id BIGINT REFERENCES floors(id) ON DELETE SET NULL, -- Link to a floor/zone
    number TEXT NOT NULL, -- Room "101", "C-01", etc.
    type TEXT DEFAULT 'Sencilla',
    base_price NUMERIC DEFAULT 0,
    status TEXT DEFAULT 'disponible', -- disponible, ocupada, limpieza, mantenimiento
    
    -- Specific Features (Beds, baths, amenities)
    features JSONB DEFAULT '{}'::jsonb,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(branch_id, number) -- Room number is unique per branch (e.g. 101 can exist in Branch A and B)
);

-- 4. Guests (Simple Guest directory)
CREATE TABLE IF NOT EXISTS guests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_type TEXT DEFAULT 'CC',
    document_id TEXT UNIQUE NOT NULL, -- Prevent duplicate guests
    full_name TEXT NOT NULL,
    phone TEXT,
    email TEXT,
    origin TEXT, -- Ciudad/País de origen
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Bookings (Reservas)
CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id BIGINT REFERENCES rooms(id) ON DELETE CASCADE NOT NULL,
    guest_id BIGINT REFERENCES guests(id) ON DELETE SET NULL,
    
    check_in TIMESTAMP WITH TIME ZONE NOT NULL,
    check_out TIMESTAMP WITH TIME ZONE NOT NULL,
    
    total_price NUMERIC DEFAULT 0,
    status TEXT DEFAULT 'reservada', -- reservada, ocupada (check-in), checkout, cancelada
    payment_status TEXT DEFAULT 'pendiente', -- pendiente, parcial, pagado
    source TEXT DEFAULT 'directo', -- directo, booking.com, whatsapp, etc.
    
    notes TEXT,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Room Charges (Consumos Extra - Restaurante, Minibar, etc.)
CREATE TABLE IF NOT EXISTS room_charges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT REFERENCES bookings(id) ON DELETE CASCADE NOT NULL,
    description TEXT NOT NULL,
    amount NUMERIC NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- *** INITIAL SEEDING ***
-- Create a default "Main Branch" so the UI never starts empty/broken
INSERT INTO branches (name, city, address)
VALUES ('Sede Principal', 'Ciudad Principal', 'Dirección Principal')
ON CONFLICT DO NOTHING;
