-- 1. Create branches table
CREATE TABLE IF NOT EXISTS branches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    city TEXT,
    address TEXT,
    phone TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Insert default branch if not exists
INSERT INTO branches (name, city, address)
VALUES ('Sede Principal', 'Ciudad Principal', 'Dirección Principal')
ON CONFLICT DO NOTHING;

-- 3. Create floors table if it doesn't exist (Handling the "relation does not exist" error)
CREATE TABLE IF NOT EXISTS floors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    floor_number INTEGER NOT NULL,
    name TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    branch_id BIGINT REFERENCES branches(id)
);

-- 4. Add branch_id to rooms table
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'rooms' AND column_name = 'branch_id') THEN
        ALTER TABLE rooms ADD COLUMN branch_id BIGINT REFERENCES branches(id);
    END IF;
END $$;

-- 5. Add branch_id to floors table if it exists but column missing (for existing installations)
DO $$ 
BEGIN 
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'floors') AND 
       NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'floors' AND column_name = 'branch_id') THEN
        ALTER TABLE floors ADD COLUMN branch_id BIGINT REFERENCES branches(id);
    END IF;
END $$;

-- 6. Populate default branch for existing records
UPDATE rooms 
SET branch_id = (SELECT id FROM branches WHERE name = 'Sede Principal' LIMIT 1)
WHERE branch_id IS NULL;

UPDATE floors 
SET branch_id = (SELECT id FROM branches WHERE name = 'Sede Principal' LIMIT 1)
WHERE branch_id IS NULL;

-- 7. Handle Uniqueness constraint for floors (Per Branch, not Global)
-- If the table was just created, it has no constraints yet (except PK).
-- If it existed, it might have a UNIQUE(floor_number) constraint which is bad for multi-branch.
DO $$ 
BEGIN 
    -- Try to drop the global unique constraint if it exists (constraint name usually floors_floor_number_key)
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'floors_floor_number_key') THEN
        ALTER TABLE floors DROP CONSTRAINT floors_floor_number_key;
    END IF;
    
    -- Add composite unique constraint if not exists
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'floors_branch_number_key') THEN
        ALTER TABLE floors ADD CONSTRAINT floors_branch_number_key UNIQUE (branch_id, floor_number);
    END IF;
END $$;
