-- 1. Create shifts table
CREATE TABLE IF NOT EXISTS shifts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cashier_name VARCHAR(100) NOT NULL,
    branch_name VARCHAR(100) DEFAULT 'Sede Principal',
    status VARCHAR(20) DEFAULT 'abierto',
    start_time TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    end_time TIMESTAMP WITH TIME ZONE,
    initial_cash DECIMAL(10, 2) DEFAULT 0,
    final_cash DECIMAL(10, 2),
    expected_cash DECIMAL(10, 2),
    digital_sales DECIMAL(10, 2) DEFAULT 0,
    difference DECIMAL(10, 2),
    expenses JSONB DEFAULT '[]'::jsonb,
    metrics_snapshot JSONB
);

-- 2. Add shift_id column to orders
ALTER TABLE orders 
ADD COLUMN IF NOT EXISTS shift_id BIGINT REFERENCES shifts(id);

-- Optional: Index for faster queries
CREATE INDEX IF NOT EXISTS idx_orders_shift_id ON orders(shift_id);
