-- Create floors table
CREATE TABLE IF NOT EXISTS floors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    floor_number INTEGER UNIQUE NOT NULL,
    name TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Populate with existing floors from rooms table to avoid breaking current view
INSERT INTO floors (floor_number, name)
SELECT DISTINCT floor, 'Piso ' || floor
FROM rooms
WHERE floor IS NOT NULL
ON CONFLICT (floor_number) DO NOTHING;

-- Optional: Add constraint to rooms if you want to enforce strictness, 
-- but for now we can leave it loose to avoid migration errors with existing data.
