-- !!! WARNING: THIS WILL DELETE ALL HOTEL DATA !!!
DROP TABLE IF EXISTS room_charges CASCADE;
DROP TABLE IF EXISTS bookings CASCADE;
DROP TABLE IF EXISTS rooms CASCADE;
DROP TABLE IF EXISTS floors CASCADE;
DROP TABLE IF EXISTS branches CASCADE;
DROP TABLE IF EXISTS guests CASCADE;
