-- =============================================
-- MIGRACIÓN FASE 1: INVENTARIO Y MENÚ
-- =============================================

-- 1. Tabla de Categorías
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  icon text,
  created_at timestamptz default now()
);

-- 2. Tabla de Productos
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  category_id bigint references public.categories(id),
  name text not null,
  description text,
  price numeric not null,
  image text,
  stock int default 0,
  stock_threshold int default 5,
  available boolean default true,
  
  -- Guardaremos arrays y objetos como JSONB para flexibilidad
  base_ingredients jsonb default '[]'::jsonb, -- ["Pan", "Carne"]
  extras jsonb default '[]'::jsonb,           -- [{"name": "Queso", "price": 2000}]
  branch_prices jsonb default '{}'::jsonb,    -- {"Sede Norte": 15000}
  
  created_at timestamptz default now()
);

-- 3. Habilitar Realtime (Para que el menú se actualice solo)
alter publication supabase_realtime add table public.categories;
alter publication supabase_realtime add table public.products;

-- 4. Políticas de Seguridad (RLS)
-- Por ahora, permitimos lectura/escritura pública para facilitar la migración sin login complejo inicial.
-- En producción, esto debería restringirse a usuarios autenticados.

alter table public.categories enable row level security;
alter table public.products enable row level security;

create policy "Acceso Publico Categorias" on public.categories for all using (true) with check (true);
create policy "Acceso Publico Productos" on public.products for all using (true) with check (true);

-- 5. Datos Iniciales (Opcional - Migrar lo básico si está vacío)
-- Solo insertamos si la tabla está vacía para no duplicar en ejecuciones futuras
do $$
begin
  if not exists (select 1 from public.categories) then
    insert into public.categories (name, icon) values
    ('Hamburguesas', '🍔'),
    ('Salchipapas', '🍟'),
    ('Bebidas', '🥤');
  end if;
end $$;
