-- =============================================
-- MIGRACIÓN FASE 2: PEDIDOS ACTIVOS
-- =============================================

-- 1. Tabla de Pedidos (Orders)
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  customer_name text,
  table_number text, -- Puede ser "Mesa 1", "Para Llevar", "Domicilio"
  status text default 'nuevo', -- 'nuevo', 'fabricacion', 'despachado', 'pagado', 'cancelado'
  total numeric default 0,
  payment_method text, -- 'efectivo', 'nequi', 'tarjeta'
  delivery_address text, -- Para domicilios
  notes text,
  preparation_time_seconds int, -- Tiempo en segundos desde creación hasta pago
  dispatched_at timestamptz, -- Fecha/hora de despacho
  created_at timestamptz default now()
);

-- 2. Tabla de Items del Pedido (Order Items)
create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references public.orders(id) on delete cascade,
  product_id bigint references public.products(id), -- Opcional, por si se borra el producto
  product_name text not null, -- Guardamos el nombre por si cambia el original
  quantity int default 1,
  price numeric not null, -- Precio unitario en el momento de la compra
  customization jsonb default '{}'::jsonb, -- { "ingredients": ["Sin cebolla"], "extras": [...] }
  created_at timestamptz default now()
);

-- 3. Habilitar Realtime (CRÍTICO para la cocina)
alter publication supabase_realtime add table public.orders;
alter publication supabase_realtime add table public.order_items;

-- 4. Políticas de Seguridad (Abiertas por ahora)
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

create policy "Public Access Orders" on public.orders for all using (true) with check (true);
create policy "Public Access Items" on public.order_items for all using (true) with check (true);
